/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-low": "#131b2e",
                "inverse-primary": "#00687a",
                "surface-container-lowest": "#0a0e18",
                "outline": "#869397",
                "on-tertiary-container": "#4edea3",
                "tertiary-container": "#1bbd85",
                "error": "#ffb4ab",
                "on-secondary": "#002e6a",
                "primary-fixed": "#acedff",
                "on-tertiary-fixed": "#002113",
                "on-surface-variant": "#94a3b8",
                "on-background": "#dfe2f1",
                "surface-variant": "#1e293b",
                "on-secondary-fixed": "#001a42",
                "surface-dim": "#0b0f19",
                "tertiary": "#4edea3",
                "on-secondary-fixed-variant": "#004395",
                "on-tertiary-fixed-variant": "#005236",
                "primary-fixed-dim": "#4cd7f6",
                "inverse-on-surface": "#2c303b",
                "inverse-surface": "#dfe2f1",
                "tertiary-fixed": "#6ffbbe",
                "on-tertiary": "#003824",
                "surface-tint": "#4cd7f6",
                "secondary": "#38bdf8",
                "surface-bright": "#353944",
                "surface-container-highest": "#1e293b",
                "surface-container-high": "#161f30",
                "on-primary": "#003640",
                "on-error": "#690005",
                "on-primary-fixed-variant": "#004e5c",
                "on-surface": "#f1f5f9",
                "primary": "#06b6d4",
                "primary-container": "#0891b2",
                "surface": "#0b0f19",
                "on-primary-container": "#00424f",
                "outline-variant": "#1e293b",
                "tertiary-fixed-dim": "#4edea3",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                "background": "#0b0f19",
                "secondary-container": "#0566d9",
                "surface-container": "#0f172a"
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem"
            },
            spacing: {
                "grid-pattern-size": "20px",
                "gutter-sm": "0.75rem",
                "gutter-md": "1rem",
                "topbar-height": "4rem",
                "sidebar-collapsed": "4.5rem",
                "margin-page": "2rem",
                "gutter-lg": "1.5rem",
                "sidebar-expanded": "16rem"
            },
            fontFamily: {
                "body-lg": ["Geist", "sans-serif"],
                "label-sm": ["JetBrains Mono", "monospace"],
                "body-sm": ["Geist", "sans-serif"],
                "body-md": ["Geist", "sans-serif"],
                "stat-counter": ["JetBrains Mono", "monospace"],
                "display-lg": ["Geist", "sans-serif"],
                "headline-sm": ["Geist", "sans-serif"],
                "headline-md": ["Geist", "sans-serif"],
                "headline-lg": ["Geist", "sans-serif"],
                "label-md": ["JetBrains Mono", "monospace"],
                "mono": ["JetBrains Mono", "monospace"],
                "sans": ["Geist", "sans-serif"]
            }
        },
    },
    plugins: [],
}